fetch: Add row count per file to blob resource
cockroachdb/molt pull request #114
Opened 2024-01-12 20:41 UTC by Jeremyyang920

This commit adds a row count field to ever storage resource. The reason for this is mainly for progress tracking but more specfically for the IMPORT use case where we are not able to know the number of rows imported. We now have this information since each resource has its own file count.

Release note: None

2024-01-16 18:19 UTC, ryanluu12345 commented
Could you please add results of your manual testing with each fetch mode? I mainly want to see it hasn't regressed. Or even better, run the E2E tests on this branch?

2024-01-16 18:19 UTC, ryanluu12345 commented on fetch/csv_pipe.go
> +// Flush flushes the current csv files when either
Super nit: `// flush` since the method is lower cased

2024-01-16 19:21 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
If the flush fails then we exit the program anyways so the ordering here doesn't really matter.

2024-01-16 19:29 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +	newWriter func(numRowsCh chan int) io.WriteCloser
Because of the way newWriter is defined as a closure on the csvPipe object and where file resources get created, a channel has to be used because its the only form of way of updating data to this go routine. Its also the most idomatic way of passing data between go routines.

2024-01-16 19:36 UTC, ZhouXing19 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
I also found a mismatch here. 

In `csvPipe.flush()`, we first `p.numRowsCh <- p.currRows` and then `p.csvWriter.Flush()`, while in the parallel goroutine, we have `gcpStore.CreateFromReader()` first call `io.Copy(wc, r);` and then `rows := <-numRows`. IIUC `p.numRowsCh` is a blocking channel, so it actually seems a deadlock to me. Thus I wonder if we should call `rows := <-numRows` before `io.Copy(wc, r);` in `gcpStore.CreateFromReader()`.

2024-01-16 19:40 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
p.numRowsCh is not blocking as its buffered.

2024-01-16 19:52 UTC, ZhouXing19 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
Ok makes sense that it is not a deadlock, but if error happens `CreateFromReader()` returns with err prior to `rows := <-numRows`, the _next_ iteration of `p.flush()` in the for-loop in `Pipe()` will still be blocked, as the `numRows` is still full, making the main program hang at `err := pipe.Pipe(table.Name)` in `func exportTable()`.

2024-01-16 20:00 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
If im not mistaken we exit the file creation process at that point, the error from p.flush() the error channels passes it along and we exit this process completely.

2024-01-16 20:03 UTC, ZhouXing19 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
> the error from p.flush() the error channels passes it along 

The error is pushed to `writerErrCh` in `exportTable()`, but `writerErrCh` is read only after `pipe.Pipe()` returns. The case I had in mind is that `pipe.Pipe()` hangs, and `writerErrCh` will never be read.

2024-01-16 20:10 UTC, ZhouXing19 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
The story line I had in mind is:
1. In the 1st iteration of the for-loop in `csvPipe.Pipe()`, we call `p.flush()`, which do `p.numRowsCh <- p.currRows; p.csvWriter.Flush()`, and return immediately. i.e. we will enter the 2nd iteration immediately. 
2. In parallel, the `gcpStore.CreateFromReader()` returned with error at `io.Copy(wc, r)`, without emptying  `numRowsCh`. The error is written to `writerErrCh` in `exportTable()`
3. In the 2nd iteration, `p.flush()` now hangs, as `p.numRowsCh` is still full. It means `pipe.Pipe()` hangs.
4. At this moment, back to the main program -- `exportTable()` --, it hangs at `err := pipe.Pipe(table.Name)`, while `case werr := <-writerErrCh:` actually is unreachable.

2024-01-16 20:32 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
Sorry yes, you are correct. So its actually just an ordering thing of reading off the channel. The issue I was going to describe was a thing I saw with S3 and why I had the read after, but because I send the data first in csv_pipe before flush, the ordering of the read inside the CreateFromReader() call won't matter and I can do that before possible errors.

2024-01-16 20:33 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
But looking through this thread now, we need to add a test case around more errors since none of our existing tests would have caught a this.

2024-01-16 22:02 UTC, ryanluu12345 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
Yes I agree, we should add some datadriven tests for this case. Or if not appropriate, can add tests that simulate these cases and verify deadlocks/timeouts don't occur.

2024-01-17 07:16 UTC, ryanluu12345 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
Based on what Jane is describing for the ordering of reading off the channel, does that mean we just need to read the error of the channel before the numRows? Would that end up working?

2024-01-17 07:16 UTC, ryanluu12345 requested changes
Pending the ordering changes mentioned in the thread to avoid blocking behavior.

2024-01-17 11:05 UTC, ZhouXing19 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
Thinking about it more, I think there's a bug that is here originally and a better exit rule for Pipe() is needed -- the writer creation part should be able to communicate with it if error happens. I will need some time to think and test more to confirm this tho...

2024-01-17 16:27 UTC, Jeremyyang920 commented on fetch/csv_pipe.go
> +		p.numRowsCh <- p.currRows
TLDR: Its note even just the ordering of things really that is the problem. Io.Pipe operations with copy are blockng operations that can also prevent channel processing. So there is a delicate balance here of ensuring things don't block when its not supposed to.

2024-01-18 20:33 UTC, Jeremyyang920 commented
Closing this pr as Jane will take it across the line with the bug fixes since the row count isint urgent.

2024-01-18 20:33 UTC, closed without merging

2024-02-05 17:20 UTC, ZhouXing19 commented
Note here as well: implementation from this PR is merged with #125 but that PR doesn't include tests for the original row count add-on for each blob storage, it only includes test for the deadlock issue. The test is tracked in this jira ticket: https://cockroachlabs.atlassian.net/browse/CC-27091