[CC-26909] fetch: Add CreateFromContinuationPoint to datablob interface
cockroachdb/molt pull request #119
Opened 2024-01-19 23:10 UTC by Jeremyyang920

This commit adds the CreateFromContinuationPoint functionality to the S3 and GCP data stores. This allows us to return the list of files that should be proceseed for a subsequent run of fetch after an exception occured.

Release note: None

2024-01-22 20:33 UTC, Jeremyyang920 commented on go.mod
> +	github.com/googleapis/google-cloud-go-testing v0.0.0-20210719221736-1c9a4c676720
This dependency is technically archived, but because its mostly just interfaces for testing, I think its fine to bring in. Google was pushing to not use mocks at all for their testing which is evident with the way the go SDK is structured.

2024-01-22 22:04 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp_test.go
> +}
The reason for needing to mock this way is due to the way GCP calls need to be made and how dependency injection doesnt really work cleanly.

`it := client.Bucket(bucket).Objects(ctx, &storage.Query{
		Prefix: prefix,
		// The StartOffeset parameter is similar to the StartAfter flag
		// for S3 except that it is inclusive of the key so
		// we don't need to do any extra filtering of the
		// results.
		StartOffset: key,
	})`

Noticed the chained call of client.Bucket.Object() but we can really only pass in the root level client interface easily from the way the rest of the code is set up which makes sense. So in order for the Objects call to return the right thing we needed to mock Bucket and Objects to conform to their interfaces and then can mock the return value.

2024-01-22 22:09 UTC, ryanluu12345 commented on fetch/datablobstorage/gcp.go
> +	if s.bucketPath != "" {
Could you add a short comment why this formatting is different in the case where bucket path is empty? Even as the person who implemented this flag it took me a second to remember why this logic needs to happen.

2024-01-22 22:10 UTC, ryanluu12345 commented on fetch/datablobstorage/gcp.go
> +		// The StartOffeset parameter is similar to the StartAfter flag
Clean!

2024-01-22 22:11 UTC, ryanluu12345 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
Is there a chance that this could accidentally pick up extra or conflicting files? The scenario I'm thinking about is:
1. User runs full fetch and it succeeds, but the intermediate store is not cleaned up
2. User runs full fetch with same exact store path and it fails, leaving you with a continuation token; store is not cleaned up
3. Now the bucket has the files from the first and second runs. It's unclean and not representative of the data that needs to be moved.

2024-01-22 22:13 UTC, ryanluu12345 commented on fetch/datablobstorage/local.go
> +func (l *localStore) CreateFromContinuationPoint(
If this is a TODO, please specify it as such and add a ticket.

2024-01-22 22:13 UTC, ryanluu12345 commented on fetch/datablobstorage/s3.go
> +	key := fmt.Sprintf("%s/%s", table.SafeString(), fileName)
Actually think that this logic to get the key/prefix/etc. could be wrapped up in a helper method so that you don't have to write this twice.

```
getKeyAndPrefix(table dbTable.name) (string, string) {
....
}
```

2024-01-22 22:15 UTC, ryanluu12345 requested changes
Mostly small comments, but helpful for future clarity.

2024-01-22 22:27 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp.go
> +		// The StartOffeset parameter is similar to the StartAfter flag
Yes. We name the files lexicographically so we are assuming that contract holds true.

2024-01-22 22:31 UTC, Jeremyyang920 commented on fetch/datablobstorage/local.go
> +func (l *localStore) CreateFromContinuationPoint(
Oh I forgot we had file path as a flag for local. I was thking it was tmp directory in which case I would have said we don't need to do it. But Ill add the logic for it.

2024-01-22 22:35 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
If you ran it with the same parameters and the same file chunks, then all parts will be overwritten the second run.

The only issue that would happen is if the user chooses to do less chunks and something fails, as the contiuation token process would pick up all files (even ones that might not be part of the new process), but this seems more of a user error than something we can code against since we would never know.

2024-01-22 22:42 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp.go
> +	key := fmt.Sprintf("%s/%s", table.SafeString(), fileName)
Im not going to make the formatting a constant since its different from the one used to create a file and I moved the key prefix to a helper so its only used there once.

2024-01-23 00:08 UTC, Jeremyyang920 commented on fetch/datablobstorage/local.go
> +func (l *localStore) CreateFromContinuationPoint(
Implementation done. Going to add the mock os tests for it tomorrow.

2024-01-23 16:27 UTC, ZhouXing19 commented on fetch/datablobstorage/datablobstorage.go
> +	CreateFromContinuationPoint(ctx context.Context, table dbtable.VerifiedTable, fileName string) ([]Resource, error)
nit: I was a bit confused by the name of this function at first and then realized this func doesn't actually create a new file in the bucket, but list out the files that are already on the bucket. 
I.e. `CreateFromReader` calls `s.client.Bucket(s.bucket).Object(key).NewWriter(ctx)` to create new files, but `CreateFromContinuationPoint` calls `client.Bucket(bucket).Objects()` to list out the existing ones. 

So just to confirm if I understood the story line here correctly: `CreateFromContinuationPoint` is called only when `exportTable()` has finished successfully, but `importTable()` failed from previous fetch attempt. We just want to have `importTable()` restarts from the continuation point for the next attempt.

If this is correct, I wonder if we can rename this function to `ListFromContinuationPoint`, to be in contrast with `CreateFromReader`. Also, comments inline to distinguish these 2 funcs would be helpful!

2024-01-23 16:31 UTC, Jeremyyang920 commented on fetch/datablobstorage/datablobstorage.go
> +	CreateFromContinuationPoint(ctx context.Context, table dbtable.VerifiedTable, fileName string) ([]Resource, error)
Your understanding is correct. I wanted to keep the naming somewhat consistent, but I can change it to your suggestion.

2024-01-23 16:53 UTC, Jeremyyang920 commented on fetch/datablobstorage/datablobstorage.go
> +	CreateFromContinuationPoint(ctx context.Context, table dbtable.VerifiedTable, fileName string) ([]Resource, error)
I added comments at the interface definition level. Let me know if that helps!

2024-01-23 17:48 UTC, ZhouXing19 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
> if the user chooses to do less chunks

Could you say more about this? In what way (i.e. is there an option) for a user to get into this state?

2024-01-23 17:49 UTC, ZhouXing19 commented on fetch/datablobstorage/datablobstorage.go
> +	CreateFromContinuationPoint(ctx context.Context, table dbtable.VerifiedTable, fileName string) ([]Resource, error)
Yes it's crystal clear now, thanks!!

2024-01-23 18:03 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
We allow the user to specify the flush rows or the file size. If the first run they chose to say flush ever 100 files, but then reran and now did every 200. We would now have half as many files, but if they didnt delete the files from the old run, we would pick those up as its in the directory still.

2024-01-23 18:07 UTC, ZhouXing19 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
Makes sense, and seems to me that this could be a common user error. When hitting an error, user might tend to be more conservative and adjust the granularity. Tho not necessarily in this PR, it might be worth documenting or adding a hint for such possible hazard when it notices the bucket is not empty.

2024-01-23 18:34 UTC, ZhouXing19 approved these changes
LGTM, thanks for being patient with my questions!

2024-01-23 18:47 UTC, Jeremyyang920 commented on fetch/datablobstorage/gcp.go
> +	it := client.Bucket(bucket).Objects(ctx, &storage.Query{
I think this would be something we document with the Fetch docs. Or in the future it could be if we notice the bucket is not empty and its not a continuation run, then we first delete items in the bucket.

2024-01-23 22:27 UTC, ryanluu12345 commented on fetch/datablobstorage/gcp.go
> +		// The StartOffeset parameter is similar to the StartAfter flag
Makes sense. We are the ones who enforce that too, so this works.

2024-01-23 22:27 UTC, ryanluu12345 commented on fetch/datablobstorage/datablobstorage.go
> +	// a contiuation point. It will query the respective data store
Super nit: mispelling of `continuation`

2024-01-23 22:30 UTC, Jeremyyang920 commented on fetch/datablobstorage/datablobstorage.go
> +	// a contiuation point. It will query the respective data store
fixed

2024-01-23 22:30 UTC, ryanluu12345 approved these changes
LGTM thanks for this!

2024-01-23 22:30 UTC, ryanluu12345 commented on fetch/datablobstorage/local.go
> +		if f.Name() >= fileName {
TIL you can do a string comp this way

2024-01-23 22:31 UTC, ryanluu12345 commented on fetch/datablobstorage/local.go
> +	fmt.Println(baseDir)
Nit: Stray fmt.Println statement

2024-01-23 22:35 UTC, Jeremyyang920 commented on fetch/datablobstorage/local.go
> +		if f.Name() >= fileName {
You can do this in any language really since it just starts to compare the ascii values lexicographically.

2024-01-24 15:52 UTC, merged