fetch: added an exception reporter helper and integrated in copy/direct copy/import
cockroachdb/molt pull request #120
Opened 2024-01-20 00:22 UTC by ryanluu12345

Now there is a helper that parses the PG error, extracts key information necessary to store in the exception log, and writes it / links it to the fetch run. Also added in portions of the code to create the dependency tables and status runs so that the relations are correct.

Resolves: CC-26806
Release Note: None

2024-01-22 20:05 UTC, ZhouXing19 requested changes

2024-01-22 20:05 UTC, ZhouXing19 commented on fetch/copy.go
> +				fileName := key[strings.LastIndex(key, "/")+1:]
Can we use `path.Base()` to get the filename?

2024-01-22 20:05 UTC, ZhouXing19 commented on fetch/import_table.go
> +			pgErr := status.MaybeReportException(ctx, logger, baseConn.(*dbconn.PGConn).Conn, table.Name, err, "")
nit: add inline comment for this "" value with `""/* filename */`

2024-01-22 20:05 UTC, ZhouXing19 commented on fetch/status/exceptions.go
> +var fileNameRegEx = regexp.MustCompile(`(part.+csv?)`)
Should this be aligned with the file pattern used in the storage engine? For example, for gcp, it's `key := fmt.Sprintf("%s/part_%08d.%s", table.SafeString(), iteration, fileExt)`. So I wonder if we should be more strict with `%08d` in the file name regex too.

2024-01-22 22:27 UTC, ryanluu12345 commented on fetch/copy.go
> +				fileName := key[strings.LastIndex(key, "/")+1:]
Yep using it now!

2024-01-22 22:27 UTC, ryanluu12345 commented on fetch/import_table.go
> +			pgErr := status.MaybeReportException(ctx, logger, baseConn.(*dbconn.PGConn).Conn, table.Name, err, "")
Done!

2024-01-22 22:28 UTC, ryanluu12345 commented on fetch/status/exceptions.go
> +var fileNameRegEx = regexp.MustCompile(`(part.+csv?)`)
I'm not sure this is necessary because we get everything between part and csv (inclusive). I don't see a case where the intermediary store will have something that doesn't match this exact pattern unless people manually tamper with it. I'm not too concerned here.

2024-01-23 15:45 UTC, ZhouXing19 approved these changes
Mostly nit comments module the context key one. Will let Jeremy to finalize the review.

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
This is not needed -- since we have named `retErr error` as the returned value of this function, the returned error is automatically propagated as `retErr`.
Example in playground: https://go.dev/play/p/vQCz8EEtv-E

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
ditto

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
ditto

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
ditto

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
ditto

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetch.go
> +		retErr = err
ditto

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/fetchcontext/fetchcontext.go
> +const key fetchCtxKey = iota
Is this the recommended practice to define a key as an int? Seems to me it can cause collision if other keys are defined in a similar way. According to the usages of `context.WithValue()` and `ctx.Value()` in the crdb code base (example [[1](https://github.com/cockroachdb/cockroach/blob/ba52733b8f92c17e8902de81591debf04d0fb076/pkg/sql/conn_executor.go#L4486)][[2](https://github.com/cockroachdb/cockroach/blob/ba52733b8f92c17e8902de81591debf04d0fb076/pkg/roachpb/tenant.go#L140)][[3](https://github.com/cockroachdb/cockroach/blob/ba52733b8f92c17e8902de81591debf04d0fb076/pkg/sql/conn_executor.go#L4491)]), we tend to use the actual struct obj as the key. 

So I wonder if we can do something similar here:

```go
type fetchKey struct{}

type FetchReq struct {
	RunID     uuid.UUID
	StartedAt time.Time
}

func WithFetchReq(ctx context.Context, req FetchReq) context.Context {
    return context.WithValue(ctx, fetchKey{}, req)
}

func FetchReqFromCtx(ctx context.Context) FetchReq {
	req := ctx.Value(fetchKey{})
	if req == nil {
		return FetchReq{}
	}
	return req.(FetchReq)
}
```

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/status/exceptions.go
> +const excludedSqlState = "42704"
Can we add some comments inline for this exception? IIUC, this error code stands for `undefined_object`, but in which cases do we see this error?

2024-01-23 15:45 UTC, ZhouXing19 commented on fetch/status/exceptions.go
> +var fileNameRegEx = regexp.MustCompile(`(part.+csv?)`)
OK sounds good to me!

2024-01-23 15:53 UTC, Jeremyyang920 commented on fetch/copy.go
> +				return pgErr
nit: since we dont use pgErr again, lets just do `return status.MaybeReportException`

2024-01-23 15:59 UTC, Jeremyyang920 commented on fetch/fetch.go
> +		Status:        status.StatusInProgress,
Are we still going with Status based on comments from Adam on the design doc?

2024-01-23 16:07 UTC, Jeremyyang920 commented on fetch/status/exceptions.go
> +	// TODO: figure out to deduplicate or upsert and do nothing if conflict.
Not needed to be addressed here, but how can we duplicate rows if createdAt is a time.Now() column.

2024-01-23 16:11 UTC, Jeremyyang920 commented on fetch/fetch_test.go
> +	t.Run("successfully initiliazed when tables not created", func(t *testing.T) {
nit: initialized spelling

2024-01-23 16:12 UTC, Jeremyyang920 commented on fetch/fetch_test.go
> +	t.Run("successfully initiliazed when tables created beforehand", func(t *testing.T) {
same spelling note as above

2024-01-23 16:18 UTC, Jeremyyang920 commented on fetch/status/exceptions.go
> +		}
Did we store status code as an int in the table? I dont't think we can do that. Some codes have characters in them
https://github.com/cockroachdb/cockroach/blob/786ed22e6c319b8d28399f8ee1f82b88efe7c1ef/pkg/sql/pgwire/pgcode/codes.go#L326

2024-01-23 16:34 UTC, Jeremyyang920 reviewed
Mostly looks good to me, barring the comment from Jane about the ctx that needs addressing.

2024-01-23 20:12 UTC, ryanluu12345 commented on fetch/fetch.go
> +	targetPgxConn := conns[1].(*dbconn.PGConn).Conn
Good suggestion! Let me do this!

2024-01-23 20:13 UTC, ryanluu12345 commented on fetch/fetch.go
> +		retErr = err
Thanks for the note here. Makes perfect sense to me!

2024-01-23 20:14 UTC, ryanluu12345 commented on fetch/fetchcontext/fetchcontext.go
> +const key fetchCtxKey = iota
Yep, I like this method better. I went ahead and made the change.

2024-01-23 20:15 UTC, ryanluu12345 commented on fetch/status/exceptions.go
> +const excludedSqlState = "42704"
@Jeremyyang920 I took this bit from your testing. Wondering if you have insights on when you hit this.

2024-01-23 20:15 UTC, ryanluu12345 commented on fetch/copy.go
> +				return pgErr
Good point!

2024-01-23 20:15 UTC, ryanluu12345 commented on fetch/fetch.go
> +		Status:        status.StatusInProgress,
I plan to discuss that in our weekly today. For now I'm keeping it but we can certainly remove this later.

2024-01-23 20:16 UTC, ryanluu12345 commented on fetch/status/exceptions.go
> +	// TODO: figure out to deduplicate or upsert and do nothing if conflict.
By duplicate I mean on the retries that `import` does by default. It creates a new row for each of these. So I mean deduplicate the error message + details. Not the time it occurred, because technically they are 3 different retries.

2024-01-23 20:17 UTC, ryanluu12345 commented on fetch/fetch_test.go
> +	t.Run("successfully initiliazed when tables not created", func(t *testing.T) {
Thanks!

2024-01-23 20:17 UTC, Jeremyyang920 commented on fetch/status/exceptions.go
> +const excludedSqlState = "42704"
I took that from code that exists inside Fetch already.

2024-01-23 20:25 UTC, ryanluu12345 commented on fetch/status/exceptions.go
> +		}
Yep, good point. I ended up switching it from an int to a string and change the mapping columns everywhere too. Works!

2024-01-23 20:26 UTC, ryanluu12345 commented on fetch/status/exceptions.go
> +const excludedSqlState = "42704"
@ZhouXing19 I left a comment for what it represents. Let's just leave it at that.

2024-01-23 21:25 UTC, Jeremyyang920 approved these changes

2024-01-23 22:37 UTC, merged