bin: introduced the bin directory and added the initial CLI build along with README
cockroachdb/molt pull request #17
Opened 2023-08-31 21:14 UTC by ryanluu12345

This introduces the new molt-lms-cli binary so that it is available for customers to easily access. This is currently distributed as a binary since the source code is currently coupled to other packages in another private repository. The plan here is to decouple the CLI and bring it over to this repository once that work is completed. For now, there will be automation to sync changes to the CLI

Release Note: None

2023-08-31 21:54 UTC, Jeremyyang920 commented on bin/lms/README.md
> +There will be an automation piece that will make sure that any new builds of the `molt-lms-cli` in the private repository (`crdb-proxy`) will generate a pull request to update the version in this rep
This section can probably be removed besides the description of what it is. The rest of the details like private repo and stuff can be removed. 

Only thing in here really should be how to use it.

2023-09-01 23:37 UTC, ryanluu12345 commented on bin/lms/README.md
> +./molt-lms-cli help
Ok good point. I updated.

2023-09-01 23:37 UTC, ryanluu12345 commented on bin/lms/README.md
> +There will be an automation piece that will make sure that any new builds of the `molt-lms-cli` in the private repository (`crdb-proxy`) will generate a pull request to update the version in this rep
Yep, I gave a brief description of the CLI and removed all of the repo description stuff.

2023-09-04 04:55 UTC, otan requested changes
i'm going to advise against doing it this way for a few reasons:
* this makes the git repo big - at least 26MB per binary, per platform, per version
* coordinating the repo's versioning and molt lms cli's versioning will be tricky

instead, we should consider uploading versions onto an s3 bucket (or some alternate static mirror) for each platform that's easily downloadable. molt does it using the `artifacts` on each release which is valid too, but that involves making `molt lms` public which i think we want to avoid (for now).

2023-09-06 06:07 UTC, closed without merging