fetch and verify: added a flag to show or hide connection details logging
cockroachdb/molt pull request #255
Opened 2024-05-16 17:21 UTC by ryanluu12345

Previously, molt could leak connection strings in the logging in the case wrong strings are passed in. However, with the latest change, the default state is more secure and gives a general error letting the user know that connecting to the database failed. In the case the user overrides the flag, then the full connection details can be shown, allowing the user to debug.

Resolves: CC-28264
Release Note: None

**Testing**
Before
```
unable to parse url: postgres://root:%6@localhost:26257/molt?sslmode=disable: parse "postgres://root:%6@localhost:26257/molt?sslmode=disable": invalid URL escape "%6"
exit status 1
```

After (in case of flag default)
```
failed to connect to source or target database
```

After (in case of flag enabled)
```
unable to parse url: postgres://root:%6@localhost:26257/molt?sslmode=disable: parse "postgres://root:%6@localhost:26257/molt?sslmode=disable": invalid URL escape "%6"
exit status 1
```

2024-05-16 21:30 UTC, yecs1999 requested changes

2024-05-16 21:30 UTC, yecs1999 commented on fetch/fetch.go
> +			// It's safe to just allow logging if the user overrides the flag.
So are we still redacting if the flag is set to false? this comment makes it seem it's difficult to redact this command. Or are we just not showing any logs at all in this case?

2024-05-16 21:33 UTC, ryanluu12345 commented on fetch/fetch.go
> +			// It's safe to just allow logging if the user overrides the flag.
Yeah in this case we do not redact. We just don't show the log unless you previously confirmed with the flag.

2024-05-16 21:33 UTC, ryanluu12345 commented on fetch/fetch.go
> +			// It's safe to just allow logging if the user overrides the flag.
No way to hit this code path unless the user confirms they're ok with it. Otherwise in default behavior, there is no chance this gets logged.

2024-05-16 21:38 UTC, yecs1999 commented on fetch/fetch.go
> +			// It's safe to just allow logging if the user overrides the flag.
Okay, thanks for confirming.

2024-05-16 21:39 UTC, yecs1999 approved these changes
LGTM, I want to see what the other security folks think though

2024-05-17 00:00 UTC, ZhouXing19 reviewed
LGTM. But wondering if we can add hint to a connection error that they can use this new flag to debug if the connection string they provide is incorrect?

2024-05-17 00:17 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
@taroface mainly wanted your feedback on copy here?

2024-05-17 00:17 UTC, ryanluu12345 commented on cmd/internal/cmdutil/dbconn.go
> +func MaybeHandleConnectionLogging(
@taroface , could I have your take on the copy here?

2024-05-17 00:21 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +			if retErr := cmdutil.MaybeHandleConnectionLogging(logger, cfg.ShowConnectionLogging, err); err != nil {
Good catch, yes it should be.

2024-05-17 00:22 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
Done!

2024-05-17 17:07 UTC, Jeremyyang920 commented on cmd/fetch/fetch.go
> +			if retErr := cmdutil.MaybeHandleConnectionLogging(logger, cfg.ShowConnectionLogging, err); retErr != nil {
Is this the only spot we load and check the db conns?

2024-05-17 17:14 UTC, Jeremyyang920 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
Are we hiding this flag?

2024-05-17 17:19 UTC, taroface reviewed
Some suggestions

2024-05-17 17:19 UTC, taroface commented on cmd/internal/cmdutil/dbconn.go
> +			return errors.New("accepting risk of connection string being logged was not confirmed, exiting early")
```suggestion
			return errors.New("risk of logging connection string was not confirmed; exiting early")
```

2024-05-17 17:30 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +			if retErr := cmdutil.MaybeHandleConnectionLogging(logger, cfg.ShowConnectionLogging, err); retErr != nil {
From what I see, yes:
<img width="589" alt="image" src="https://github.com/cockroachdb/molt/assets/23587815/ec212fff-edde-4416-939e-299dd4d41872">

It's just these three spots.

2024-05-17 17:31 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
@Jeremyyang920 , I guess it depends on if we want to document this. Should we add this flag to documentation? If not, we can just hide it.

2024-05-17 17:31 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
Shown == output, correct.

2024-05-17 17:33 UTC, ryanluu12345 commented on cmd/internal/cmdutil/dbconn.go
> +		fmt.Println(`Setting the --show-connection-logging flag can potentially log the full connection string. Continue (y/n)?`)
Given that this is not logging but rather a prompt for actions, I will stay consistent with other prompts for actions, which are full sentences with capital first letter.

2024-05-17 17:34 UTC, ryanluu12345 commented on cmd/internal/cmdutil/dbconn.go
> +			return errors.New("accepting risk of connection string being logged was not confirmed, exiting early")
Noted.

2024-05-17 17:34 UTC, ryanluu12345 commented on moltlogger/logger.go
> +Can be set to true to get more detail about connection failures or specific replicator commands, which contain connection string details.
Done.

2024-05-17 17:34 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
Done.

2024-05-17 17:36 UTC, ryanluu12345 commented on moltlogger/logger.go
> +		`Whether or not connection logging gets shown. False by default to prevent connection string leaks.
@taroface , just to be safe, let's hide this flag and not document it. In the case customers request this gets documented, we can do that later on.

2024-05-17 17:42 UTC, taroface approved these changes

2024-05-17 17:42 UTC, Jeremyyang920 approved these changes

2024-05-17 17:45 UTC, ryanluu12345 commented
> LGTM. But wondering if we can add hint to a connection error that they can use this new flag to debug if the connection string they provide is incorrect?

I think based on discussion above, we are going to hide this entirely. If a customer runs into issues using this to connect then we can let them know the existence of it, or make it clear to the field teams. We want to provide a secure default upfront. We'll see if this is a common problem as we see usage. In the case that it is, we can add the docs and unhide immediately.

2024-05-17 17:59 UTC, merged