molt: made the command flags and descriptions consistent with other migrations tooling
cockroachdb/molt pull request #68
Opened 2023-11-14 17:49 UTC by ryanluu12345

Made the command descriptions and flags have consistent formatting. Prioritizing full sentences and better clarity about what each flag does for both fetch and verify. Also made the help command and autocomplete hooks so that it has behavior we expect. Removed the autocomplete command because that is extraneous.

Resolves: #59
Release Note: None

2023-11-14 18:23 UTC, ZhouXing19 approved these changes
LGTM but I'll leave Jeremy and Ryan to finalize the review.

2023-11-14 18:23 UTC, ZhouXing19 commented on cmd/fetch/fetch.go
> +		"Local address to listen to for traffic.",
nit: Wondering if it would be more accurate to say "Address of a local store server to listen for traffic."

2023-11-14 18:23 UTC, ZhouXing19 commented on cmd/fetch/fetch.go
> +		"Number of rows to select at a time for the source database.",
out of curiosity, does it mean `number of rows to import` as well?

2023-11-14 18:23 UTC, ZhouXing19 commented on cmd/fetch/fetch.go
> +		"Address CockroachDB can access to connect to the --local-path-listen-addr.",
nit: personally i found it a bit confusing, but maybe it's because I'm not that familiar with the context. Does it mean `Address of data that CockroachDB can access to import from a local store`?

2023-11-14 18:25 UTC, Jeremyyang920 commented on cmd/fetch/fetch.go
> +		"Path to the GCP bucket.",
Same as AWS, but not sure if gcp has a prefix in front.

2023-11-14 18:26 UTC, Jeremyyang920 commented on cmd/fetch/fetch.go
> +		"Number of rows to select at a time for the source database.",
Should it also be `Number of rows to select at a time FROM the source db`?

2023-11-14 21:42 UTC, taroface requested changes
Left a bunch of copy changes and some questions -- hope it's ok if we take a bit more time with this.

2023-11-14 21:42 UTC, taroface commented on cmd/fetch/fetch.go
> +		"Number of rows to select at a time for the source database.",
If Jane's suggestion is true, then I suggest ```Number of source database rows to import at a time.```

2023-11-14 21:42 UTC, taroface commented on cmd/fetch/fetch.go
> +		"Compression type to use (default/gzip/none).",
Is this accurate?

```suggestion
		"Compression type to use for data import (default/gzip/none).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether to fix up any rows.",
We should probably add more detail on what "fix up" does.

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Time to pause between continuous runs.",
What are the units of time?

```suggestion
		"Amount of time to pause between continuous runs.",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether verification should continuously run on each shard.",
Ditto re: shard

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Enables live mode, which attempts to account for rows that can change in value by retrying them before marking them as an inconsistency.",
```suggestion
		"Enable live mode, which attempts to account for rows that can change in value by retrying them before marking them as inconsistent.",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether rows should be verified (otherwise, performs a more basic schema check).",
I'm not clear on what the distinction between "verified" and "basic schema check" is.

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"If set, sets a maximum number of attempts to re-verify per second.",
I assume this is live mode only.

```suggestion
		"Maximum number of row retry attempts per second (live mode only).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Maximum number of rows to retry at a time in live verification mode.",
```suggestion
		"Maximum number of rows to retry at a time (live mode only).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Maximum amount of time to wait before rows can start being retried.",
```suggestion
		"Maximum amount of time to wait before retrying rows (live mode only).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Maximum number of retries live re-verification should run before marking rows as inconsistent.",
```suggestion
		"Maximum number of retries before marking rows as inconsistent (live mode only).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Maximum amount of time live reverification should take before retrying.",
Is this still accurate?

```suggestion
		"Maximum amount of time a row retry attempt should take before retrying again (live mode only).",
```

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Amount of time live verification should initially backoff for before retrying.",
This probably needs a rephrase, but I don't know what "backoff" means in this context.

2023-11-14 21:42 UTC, taroface commented on cmd/verify/verify.go
> +		"Multiplier applied to retry after each unsuccessful live re-verification run.",
What is the multiplier for?

2023-11-15 00:45 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Local address to listen to for traffic.",
Got it!

2023-11-15 00:47 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Number of rows to select at a time for the source database.",
This is just the export. I'm going to do @Jeremyyang920 's suggestion since I think it captures it more accurately. It's the number of source database rows we are fetching.

2023-11-15 00:48 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Address CockroachDB can access to connect to the --local-path-listen-addr.",
Yeah, pretty much. I'll go with this.

2023-11-15 00:50 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Path to the S3 bucket.",
Actually now that I think about it, this is the name. I'll make this `Name of the S3 bucket`

2023-11-15 00:50 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Path to the GCP bucket.",
See comment above. But I think it should be `Name of the bucket`

2023-11-15 00:54 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Whether to use direct copy mode.",
Yeah, so direct copy mode copies the data directly from the source database to the target database without using an intermediate store.

2023-11-15 00:55 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"If set, size (in bytes) before the data source is flushed.",
Ok this should clarify: `"If set, size (in bytes) before the source data is flushed to intermediate files."`

2023-11-15 00:55 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"If set, number of rows before the data source is flushed.",
Look at comment above

2023-11-15 00:57 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Path within the bucket to write intermediate files (i.e. test-migrations/v1 with no ending slash).",
I'll take your suggestion. It should be clear if people first read the README. The intermediate files are the ones that are written to the local store or S3/GCP

2023-11-15 00:58 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Whether to truncate the table being imported to.",
Correct. I'll resolve this.

2023-11-15 00:58 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"If set, the name of a replication slot that should be created before taking a snapshot of data.",
Done

2023-11-15 00:59 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Compression type to use (default/gzip/none).",
I think I"ll keep this one as is. This compression happens on the export. The decompression happens on import.

2023-11-15 01:00 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Compression type to use (default/gzip/none).",
Compression is used throughout at different steps.

2023-11-15 01:02 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Number of shards to break down each table into while doing row-based verification.",
Looking at the code I think it means how many parts to break a certain table into. So let's say there are 10000 rows and we want to break it down to 10 shards, each shard should be 1000 rows. Not sure how to succinctly explain that though.

2023-11-15 01:06 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Number of rows to select from a table at a time.",
Ok so this one ends up scanning both of the tables. Let me know your thoughts on wording this? Maybe `Number of rows to select from row + target databases at a time.

2023-11-15 01:07 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Whether to fix up any rows.",
Correct any inconsistencies found from the `verification` run.

2023-11-15 01:07 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Time to pause between continuous runs.",
This can actually be specified as a string, so like `1h`, `2m`, etc.

2023-11-15 01:08 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Whether verification should continuously run on each shard.",
Look at above comments.

2023-11-15 01:09 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Whether rows should be verified (otherwise, performs a more basic schema check).",
So basically this option would verify the schema **AND** the data in the rows if it's enabled. In the case that this is set to `false` then only the basic schema checks (matching columns and types for schema) but not the data itself.

2023-11-15 01:10 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"If set, sets a maximum number of attempts to re-verify per second.",
Good! Done.

2023-11-15 01:12 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Amount of time live verification should initially backoff for before retrying.",
`Backoff` means how much time it should wait until it does a retry after the initial row verification failure.

2023-11-15 01:14 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Multiplier applied to retry after each unsuccessful live re-verification run.",
Based on these lines of code:
```
func (rm *Retry) Next() {
	nextDuration := rm.settings.InitialBackoff * time.Duration(math.Pow(float64(rm.settings.Multiplier), float64(rm.Iteration)))
	if rm.settings.MaxBackoff > 0 && nextDuration > rm.settings.MaxBackoff {
		nextDuration = rm.settings.MaxBackoff
	}
	rm.Iteration++
	rm.NextRetry = rm.NextRetry.Add(nextDuration)
}
```
It appears that the multiplier is for the backoff duration. So basically the amount of time to wait before next retry.

2023-11-15 01:23 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Address of data that CockroachDB can access to import from a local store.",
@taroface this could use more workshopping

2023-11-15 01:26 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Address of data that CockroachDB can access to import from a local store.",
Also not sure if this is used much. I don't see it in the README Oliver wrote. Also the `local-path-listen-addr` is the main one to set up the server to listen.

2023-11-15 01:28 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Maximum number of row retry attempts per second (live mode only).",
Need to revisit if this actually means `row retry attempts`.

2023-11-15 21:46 UTC, taroface commented on cmd/fetch/fetch.go
> +		"Whether to use direct copy mode.",
```Enable direct copy mode, which copies data directly from source to target without using an intermediate store.```

2023-11-15 21:47 UTC, taroface commented on cmd/fetch/fetch.go
> +		"If set, size (in bytes) before the data source is flushed.",
SGTM!

2023-11-15 21:47 UTC, taroface commented on cmd/fetch/fetch.go
> +		"If set, number of rows before the data source is flushed.",
```If set, number of rows before the source data is flushed to intermediate files.```

2023-11-15 21:48 UTC, taroface commented on cmd/fetch/fetch.go
> +		"Path within the bucket to write intermediate files (i.e. test-migrations/v1 with no ending slash).",
```Path within the bucket where intermediate files are written (e.g., bucket-name/v1).```

2023-11-15 21:56 UTC, taroface commented on cmd/verify/verify.go
> +		"Number of shards to break down each table into while doing row-based verification.",
I'm not sure if this is mixing in/up too much terminology, but this seems to read most clearly to me (feel free to adjust):

```Number of row-based shards into which tables are partitioned for row verification.```

2023-11-15 22:00 UTC, taroface commented on cmd/verify/verify.go
> +		"Number of rows to select from a table at a time.",
It depends on it's the combined number of source + target rows, or the number of pairs. Neither of these options sounds that elegant to me so feel free to adjust.

```Combined number of source and target rows to scan at a time.```
```Number of pairs of source and target rows to scan at a time.```

2023-11-15 22:01 UTC, taroface commented on cmd/verify/verify.go
> +		"If set, maximum number of rows to read per second during scanning per shard.",
```If set, maximum number of rows to read per second on each shard.```

2023-11-15 22:02 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether to fix up any rows.",
```Whether to fix up inconsistencies found during row verification.```

2023-11-15 22:02 UTC, taroface commented on cmd/verify/verify.go
> +		"Time to pause between continuous runs.",
```Amount of time to pause between continuous runs (e.g., 1h, 2m).```

2023-11-15 22:03 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether verification should continuously run on each shard.",
This one LGTM

2023-11-15 22:05 UTC, taroface commented on cmd/verify/verify.go
> +		"Whether rows should be verified (otherwise, performs a more basic schema check).",
```If true, verify both the schema (columns, types) and row data. If false, verify only the schema.```

2023-11-15 22:11 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"If set, number of rows before the data source is flushed.",
Got it!

2023-11-15 22:12 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Path within the bucket to write intermediate files (i.e. test-migrations/v1 with no ending slash).",
Opted for this instead: `"Path within the bucket where intermediate files are written (e.g., bucket-name/folder-name)."`

2023-11-15 22:13 UTC, taroface commented on cmd/verify/verify.go
> +		"Amount of time live verification should initially backoff for before retrying.",
I am assuming `backoff` is a technical term, so maybe this is enough:

```Amount of time to backoff before retrying row verification (live mode only).```

2023-11-15 22:14 UTC, taroface commented on cmd/verify/verify.go
> +		"Multiplier applied to retry after each unsuccessful live re-verification run.",
```Multiplier to apply to backoff duration after each failed row verification (live mode only).```

2023-11-15 22:14 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"If set, maximum number of rows to read per second during scanning per shard.",
Yeah this is clear.

2023-11-15 22:14 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Whether to fix up any rows.",
Done!

2023-11-15 22:16 UTC, taroface commented on cmd/verify/verify.go
> +		"Maximum number of row retry attempts per second (live mode only).",
Ah I see what you mean.

```Maximum number of retry attempts per second (live mode only).```

2023-11-15 22:18 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Time to pause between continuous runs.",
Good let's do it this way!

2023-11-15 22:19 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Whether rows should be verified (otherwise, performs a more basic schema check).",
Done!

2023-11-15 22:20 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Maximum number of row retry attempts per second (live mode only).",
Done!

2023-11-15 22:21 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Multiplier applied to retry after each unsuccessful live re-verification run.",
Done!

2023-11-15 22:22 UTC, taroface commented on cmd/fetch/fetch.go
> +		"Address of data that CockroachDB can access to import from a local store.",
What is the relation of the address to `--local-path-listen-addr`?

2023-11-15 22:22 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Whether to use direct copy mode.",
Done!

2023-11-15 22:25 UTC, ryanluu12345 commented on cmd/verify/verify.go
> +		"Number of shards to break down each table into while doing row-based verification.",
I'm going to stick with this: `Number of shards to break down each table into while doing row-based verification.`

I believe the edits you gave might be more confusing. Shards should be pretty self explanatory.

2023-11-15 22:32 UTC, taroface commented on cmd/verify/verify.go
> +		"Number of shards to break down each table into while doing row-based verification.",
NP! I would suggest cutting "down" from that description, but not a big deal.

2023-11-15 22:33 UTC, ryanluu12345 commented on cmd/fetch/fetch.go
> +		"Address of data that CockroachDB can access to import from a local store.",
It's defaulted to this if we don't specify. So basically we will:
1. Serve at this address
2. Cockroach will try to retrieve from this
3.

2023-11-15 22:36 UTC, taroface approved these changes
LGTM!!

2023-11-15 22:50 UTC, merged