docs/RFCS: added template for RFCs and initial MOLT fetch RFC
cockroachdb/molt pull request #73
Opened 2023-11-15 00:29 UTC by ryanluu12345

Resolves: #71
Release Note: None

2023-11-16 15:22 UTC, ZhouXing19 approved these changes
LGTM but I'll leave Adam and Jeremy to finalize the review.

2023-11-16 15:22 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
nit: outputa -> output

2023-11-16 15:22 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +2. `IMPORT INTO` from intermediary store to Cockroach: table is offline; can improve performance by using compression.
Do we want to mention the possible benefit of `IMPORT INTO`? From this paragraph it seems an inferior option compared to COPY. There might have been docs comparing IMPORT and COPY and I think it's helpful if we can link them here.

2023-11-16 15:22 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we plan on handling matching schema creation on the target DB?
Should we include plan for benchmarking / performance / correctness tests?

2023-11-16 15:22 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
Would be beneficial if we can explain or link docs about the cdc_cursor.

2023-11-16 15:22 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
I found this sentence a bit disconnected from the context. Would it be more accurate to put something like: `molt fetch enables an initial dump of bulk data and streaming of updates happening on the source database after the dump is initiated.`

2023-11-16 16:24 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +This RFC presents the case for a MOLT tool which can fetch data from a source database and import the data into Cockroach. This allows for better observability and control over performance optimizati
I know what "This allows for better observability and control over performance optimizations into Cockroach, compared to third-party migrations tools." is trying to say, but it's a bit difficult to read as is.

2023-11-16 16:29 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +The tool will migrate data from PG or MySQL tables to CockroachDB
Not a big deal, but we should maybe standardize on the naming when writing. There are instances where its referenced as "The tool" and others its "it". Maybe we should reference these all as Fetch to avoid any ambiguous interpretation.

2023-11-16 18:51 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
Noted.

2023-11-16 18:54 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +2. `IMPORT INTO` from intermediary store to Cockroach: table is offline; can improve performance by using compression.
I was looking at the docs and couldn't find a clear comparison between `IMPORT INTO` and `COPY FROM`. What makes `IMPORT INTO` so much more performant? I reordered so that `IMPORT INTO` is the first option and marked as a default.

2023-11-16 19:09 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +2. `IMPORT INTO` from intermediary store to Cockroach: table is offline; can improve performance by using compression.
Oh i don't think we need to go into tech details about why import is more performant than copy, but just wanted to note that we can mention IMPORT is fasrer then COPY: https://www.cockroachlabs.com/docs/stable/import-performance-best-practices#:~:text=IMPORT%20INTO%20is,COPY%20FROM%20instead.

2023-11-16 19:10 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +2. `IMPORT INTO` from intermediary store to Cockroach: table is offline; can improve performance by using compression.
nit: Also, iiuc, for `IMPORT INTO`, it's the _target_ table that is offline. Might worth noting that this is just the table on the crdb, while the table on the source db never goes offline.

2023-11-16 19:54 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we plan on handling matching schema creation on the target DB?
Yes, including a new section for this.

2023-11-16 19:55 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
Hmm I think that this would be a term we can assume our audience knows. Given that `CDC` cursor is a concept not specific to this tool, but for database changefeeds and tracking.

@taroface @ajstorm please let me know if this is a fair assumption to make though.

2023-11-16 19:58 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
I merged the two sentences (original and your suggestion):
```
`molt fetch` enables an initial dump of bulk data from source databases to target databases, without taking source tables offline. The scope of the initial design will support PostgreSQL and MySQL source databases.

`fetch` will output a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
to migrate live data without taking your database offline.
```

2023-11-16 20:00 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +This RFC presents the case for a MOLT tool which can fetch data from a source database and import the data into Cockroach. This allows for better observability and control over performance optimizati
Did this instead:
```
Compared to third-party migration tools, `fetch` will provide better observability, debugability, and control over performance optimizations
```

2023-11-16 20:03 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The tool will migrate data from PG or MySQL tables to CockroachDB
Yeah, much better to standardize like this!

2023-11-16 20:05 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +2. `IMPORT INTO` from intermediary store to Cockroach: table is offline; can improve performance by using compression.
Ok think I addressed with this: 
```
1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; can improve performance by using compression (recommended option because `IMPORT INTO` is fast, especially with compression).
```

2023-11-16 20:15 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we plan on handling matching schema creation on the target DB?
@ZhouXing19 let me know if this is enough detail? Look at #Testing Plan

2023-11-16 21:31 UTC, ZhouXing19 commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we plan on handling matching schema creation on the target DB?
LGTM! Thanks

2023-11-16 23:39 UTC, taroface commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
@ryanluu12345 Your comment makes sense to me. BTW, there's a typo on `outputa`.

2023-11-17 20:34 UTC, ajstorm requested changes
This is a great start.  My main comment is that the "Detailed Design" section is pretty light on internal info.  For example:

- What commands are we using for dumping from each of the dialects?
- What limitations are there on dumping files (if any)?
- What failure modes do we need to consider (i.e. what if it dies mid-dump?  mid-load?)
- How does the integration with replication work?  Are there any limitations there?
- ...

We should have enough detail in here that someone unfamiliar with the tool will know how it was built, the tradeoffs we made, and what remains to be done.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +- Status: draft/in-progress/completed/rejected/obsolete/postponed
Nit: in-progress?

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +The high level plan is to build out this functionality as part of the existing `molt` tool as a subcommand. The two key features that need to be built out are the ability to export/dump data from the
Nit: Should we mention cdc-sink here?

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +The data movement portion of a migration is a crucial step that every customer goes through when migrating to Cockroach. Although there are third party tools currently available for this task, there
Nit: The second and third sentences here don't perfectly match up.  The second talks about observability problems, while the third talks about compatibility and performance.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +`molt fetch` enables an initial dump of bulk data from source databases to target databases, without taking source tables offline.
Nit: It actually provides two mode, one of which _does_ take the table offline.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +`fetch` will output a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
Nit: I'd avoid mentioning third-party tools by name here.  We can just say "third-party tools".

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +By default, data will be imported using `IMPORT INTO`. You can use the `live` mode if you need target data to be query-able during loading, which will use `COPY FROM` instead.
Nit: Above we say the table is not taken offline and here we say that the default _is_ to take it offline.  We should try to be consistent.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +For now, schemas must be identical on both sides. This is verified upfront -
Should we talk about the fact that schemas must be manually created?  Also, that longer term we want them to be created manually?

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +## Data export
In this section it would be good to discuss exactly what happens under the covers.  Specifially, that the data always flows to the machine which is running `fetch` before making it to its final destination.  This is an important detail.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compress
It might be good if we had some performance numbers in here.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +3. `COPY FROM` source database to Cockroach directly: table is still online and query-able; data is copied directly instead of dumped to an intermediary location.
We should be clear about what we mean by "copied directly".  The data is flowing from the source to the `fetch` machine, and then onto the target.  It's only "direct" from the perspective of disk.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +`fetch` will also need a strong set of initial users to give the proper customer-facing evaluation necessary to GA. This may also not be as trusted from the outset because `fetch` is newer and not as
I'd remove this part.  I don't think that it's necessary.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +Decided to build out or own tooling because of aforementioned reasons: better visibility/observability, performance improvements, and compatibility.
I'd also remove this section

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +3. Build our own tooling
Is this really an alternative?  I thought that this is what we were proposing here.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +# Testing Plan
We should have some replication-enabled testing too.

2023-11-17 20:34 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we support other replication tools?
I'd remove this one, as it's resolved.

2023-11-17 21:02 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +For now, schemas must be identical on both sides. This is verified upfront -
@ajstorm You mean longer term we want them automatically right?

2023-11-17 21:29 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +For now, schemas must be identical on both sides. This is verified upfront -
Oops, yeah, automatically.

2023-11-20 21:14 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +- Status: draft/in-progress/completed/rejected/obsolete/postponed
Done (will push in a bit)

2023-11-20 21:16 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The high level plan is to build out this functionality as part of the existing `molt` tool as a subcommand. The two key features that need to be built out are the ability to export/dump data from the
Thoughts?
```
Later on, we plan to support streaming updates by integrating with tools such as `cdc-sink`. However, that will be scoped to a later RFC.
```

2023-11-20 21:18 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +`molt fetch` enables an initial dump of bulk data from source databases to target databases, without taking source tables offline.
This is actually just confusing wording on my end. Since the source tables technically do stay online. The target tables are the ones that don't necessarily. Changed to this. Longer but more explicit:
```
`molt fetch` enables an initial dump of bulk data from source databases to target databases. This is supported in two general modes: one that takes the target table offline so that an `IMPORT INTO` can be performed. And another, where the target table stays online and a `COPY FROM` is used.
```

2023-11-20 21:19 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +`fetch` will output a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
Done!

2023-11-20 21:19 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +Decided to build out or own tooling because of aforementioned reasons: better visibility/observability, performance improvements, and compatibility.
Done.

2023-11-20 21:20 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. Build our own tooling
Good point. Removing this from the section.

2023-11-20 21:21 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +- How do we support other replication tools?
Done!

2023-11-20 21:21 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +`fetch` will also need a strong set of initial users to give the proper customer-facing evaluation necessary to GA. This may also not be as trusted from the outset because `fetch` is newer and not as
Done!

2023-11-21 08:56 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The data movement portion of a migration is a crucial step that every customer goes through when migrating to Cockroach. Although there are third party tools currently available for this task, there
Yep, agreed. I added a parallel sentence after and then made sure to mention concerns about compatibility and performance as a follow up point.

2023-11-21 08:57 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +By default, data will be imported using `IMPORT INTO`. You can use the `live` mode if you need target data to be query-able during loading, which will use `COPY FROM` instead.
I think this is resolved now that I don't even mention the bit about not taking things offline. I think I more clearly mention that we support different modes where the target table can be taken offline or remain online.

2023-11-21 08:59 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +For now, schemas must be identical on both sides. This is verified upfront -
Understood. Made a point about this. As discussed offline, referencing this feature as something that will be explored in a future RFC.

2023-11-21 09:00 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +## Data export
I understand what you're saying here. For the case where we do a fetch that dumps to intermediary files using `COPY FROM` or `IMPORT INTO` this is true. However, we also support direct copy from the source to the target.

2023-11-21 09:01 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +## Data export
I noted this!

2023-11-21 09:02 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. `COPY FROM` source database to Cockroach directly: table is still online and query-able; data is copied directly instead of dumped to an intermediary location.
Hmm but the `COPY FROM` source to Cockroach directly should be direct right? Since we are issuing a copy from the source to target directly. Unless I'm misunderstanding how this works?

2023-11-21 09:04 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +# Testing Plan
Noted.

2023-11-21 19:56 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +It will outputa a `cdc_cursor` which can be fed to CDC programs (e.g. cdc-sink, AWS DMS)
This is an outdated diff. Resolved now.

2023-11-21 23:22 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compress
@ajstorm how are these numbers? https://cockroachlabs.slack.com/archives/C02TLESRWCB/p1690516707529709

Oliver already had done some testing. So we could probably use this. Additionally, I can also note how I can do this testing by benchmarking with the latest scale testing.

2023-11-22 16:14 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +The high level plan is to build out this functionality as part of the existing `molt` tool as a subcommand. The two key features that need to be built out are the ability to export/dump data from the
SGMT

2023-11-22 18:26 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compress
I think it's fine to lean on those results, but we may also want to mention some end-to-end Fetch results which do the pulling and the IMPORT/COPY.

2023-11-22 18:28 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +3. `COPY FROM` source database to Cockroach directly: table is still online and query-able; data is copied directly instead of dumped to an intermediary location.
That may be the case.  I thought that when we met in person you said that flowing directly from the source to target was not possible?  Or maybe it's only possible when there's a "direct" fetch?  Would be worth confirming.

2023-11-22 19:02 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The dump of the data can be achieved by two main methods:
`The user has the option to dump the data in two different ways:`

Basically, one takes the **target** table offline (`IMPORT INTO`). The other keeps the target table online (`COPY FROM`)

2023-11-22 19:03 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The dump of the data can be achieved by two main methods:
Oh sorry, scratch that. This is a different context. Basically, these are the two methods we are considering under the hood.

2023-11-22 19:06 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The dump of the data can be achieved by two main methods:
```
We have two options in how we implement the data export:

- Running a direct COPY with a target of CSV or compressed CSV files: easier to implement, but slower
- Selecting all tables and paginating through all of the data: more complexity, fine grained control, more performant

For the initial version, using `COPY` directly works fine, however we want to move to a model where we can paginate through all the data by selecting data from each of the tables.
```

2023-11-22 19:06 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +`fetch` will initiate a CSV dump by going through each table in the source table. This initial dump phase can support both compressed (.gzip, .bzip) and uncompressed types.
Exactly, good catch. Will update to `source schema`.

2023-11-22 19:08 UTC, ryanluu12345 commented
Addressed this too: https://github.com/cockroachdb/molt/pull/73#discussion_r1402381950

2023-11-22 19:28 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
Tracing the code, I see the following:
1. Source gets initialized. Note that `conns[1]`  is passed in. This relates to the target conn.
```
case directCRDBCopy:
				src = datablobstorage.NewCopyCRDBDirect(logger, conns[1].(*dbconn.PGConn).Conn)
```
2. This source's reader seems to run a `CopyFrom` the source table:
```
func (c *copyCRDBDirect) CreateFromReader(
	ctx context.Context, r io.Reader, table dbtable.VerifiedTable, iteration int, fileExt string,
) (Resource, error) {
	conn, err := pgx.ConnectConfig(ctx, c.target.Config())
	if err != nil {
		return nil, err
	}
	c.logger.Debug().Int("batch", iteration).Msgf("csv batch starting")
	if _, err := conn.PgConn().CopyFrom(ctx, r, dataquery.CopyFrom(table)); err != nil {
		return nil, errors.CombineErrors(err, conn.Close(ctx))
	}
	c.logger.Debug().Int("batch", iteration).Msgf("csv batch complete")
	return nil, conn.Close(ctx)
}
```
3. In the action `export` fetch command, this is the logic that executes that uses `CreateFromReader`
```
pipe := newCSVPipe(sqlRead, logger, cfg.FlushSize, cfg.FlushRows, func() io.WriteCloser {
		resourceWG.Wait()
		forwardRead, forwardWrite := io.Pipe()
		wrappedWriter := getWriter(forwardWrite, cfg.Compression)
		resourceWG.Add(1)
		go func() {
			defer resourceWG.Done()
			itNum++
			if err := func() error {
				resource, err := datasource.CreateFromReader(ctx, forwardRead, table, itNum, importFileExt)
				if err != nil {
					return err
				}
				ret.Resources = append(ret.Resources, resource)
				return nil
			}(); err != nil {
				logger.Err(err).Msgf("error during data store write")
				if err := forwardRead.CloseWithError(err); err != nil {
					logger.Err(err).Msgf("error closing write goroutine")
				}
				writerErrCh <- err
			}
		}()
		return wrappedWriter
	})
```

Based on the logic above, it looks like the data goes directly from the source to the target, using the `COPY FROM` command. This means data is moved directly.

2023-11-22 19:31 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +3. [E2E testing](https://github.com/cockroachdb/molt/issues/36)
I think we can unlink these github issues as they won't be tracked here anymore.

2023-11-22 19:33 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +   This was strongly considered, but private labeling would leave us with the same lack of visibility into tooling and supporting changes to source code to provide better compatibility/perf for Cockr
The second half of this sentence doesn't flow that well especially after the and. I think its missing a word, or can be rephrased.

2023-11-22 19:36 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
Zooming on this particular line, I do see a nuance though. Even though the data is copied from source to target, it looks like it passes through the `fetch` tool since `fetch` is facilitating this `COPY` from source to target and it passes through the `io.Reader`
```
if _, err := conn.PgConn().CopyFrom(ctx, r, dataquery.CopyFrom(table)); err != nil {
		return nil, errors.CombineErrors(err, conn.Close(ctx))
	}
```

2023-11-22 19:42 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
Ok so I'll point out these key points:
- Direct copy mode allows `fetch` to `COPY FROM` the source to the target
- The data will still pass through `fetch` because it's in charge of coordinating `COPY FROM` and holds onto both DB connections during the process; so compute is still important
- No additional data is stored in an intermediary store or files

2023-11-22 19:56 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. [E2E testing](https://github.com/cockroachdb/molt/issues/36)
Cool, thanks!

2023-11-22 19:56 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. [E2E testing](https://github.com/cockroachdb/molt/issues/36)
Done

2023-11-22 20:03 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
Reviewed this with @Jeremyyang920 offline and I think we have a good understanding here. I'll make sure to call out these constraints. 

TLDR; direct-copy is the most direct way we can copy from source to target since we coordinate the source to target `COPY FROM`

2023-11-22 20:04 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +## Data export
Done

2023-11-22 20:10 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. `COPY FROM` source database to Cockroach directly: table is still online and query-able; data is copied directly instead of dumped to an intermediary location.
See here: https://github.com/cockroachdb/molt/pull/73#discussion_r1402646616

I need to point out this nuance that data still passes through the machine that `fetch` is running on.

2023-11-22 20:15 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +3. `COPY FROM` source database to Cockroach directly: table is still online and query-able; data is copied directly instead of dumped to an intermediary location.
Refactored this section to:
```
1. `IMPORT INTO` from intermediary store to Cockroach:

- Target table is taken offline
- Supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compression).

2. `COPY FROM` (`live` mode) from intermediary store to Cockroach:

- Table is still online and queryable; the intermediary store is used, instead of directly from the database
- Compression can't be supported here because `COPY FROM` currently doesn't have a `decompress` feature

3. Direct `COPY FROM` source database to Cockroach without intermediary store

- Table is still online and query-able
- Data is copied from the source to target without intermediary store or files
- Data still passes from the source to `fetch`, but in memory; this means that the RAM specs of the execution machine must be appropriately sized
```

2023-11-22 20:25 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compress
Added this section:
```
### Testing for Import Into vs. Copy

For Cockroach, `IMPORT INTO` is much faster, as noted above.

Previously, our team performed baseline testing on `IMPORT INTO` vs. `COPY`:
For 10M rows:

- `IMPORT INTO` (PG -> s3 CSVs -> CRDB) took 90s, 30s to upload the files to S3 and 60s to ingest it
- `COPY` (PG output directly into CRDB input) took around 350s (~6 mins) using 4MB COPY chunks.

Follow up parameter tuning notes:

- Using 1MB `COPY` chunks tooks 5mins instead of 6mins from PG->CRDB
- Using `COPY` to migrate from Postgres -> Postgres took 120s using 1MB COPY chunks and 95s using 4MB chunks. Suffice to say, IMPORT is comparable to PG COPY.
```

2023-11-22 20:34 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +1. `IMPORT INTO` from intermediary store to Cockroach: target table is taken offline; supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compress
Ok also added the fetch scale testing results so far. Two more tests to run for the `COPY` cases.

2023-12-11 21:55 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +1. AWS DMS test (uses `COPY`): 33 minutes
Is this line entry for comparing how long our DMS roachprod test takes? Since we know that this in theory is way faster when set up correctly so not sure if this is fair to DMS for this benchmark.

2023-12-11 21:58 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +4. `COPY FROM` directly without intermediate store: 47 minutes
This is just a side comment, but I brought it up briefly last week that we know there are definitely still areas of improvement here in terms of how the process is run so we may want to investigate those and retest. But not a must for this first draft of the RFC

2023-12-12 15:33 UTC, Jeremyyang920 commented on docs/RFCS/20231113_molt_fetch.md
> +The data export process is primarily limited by the dialects supported (mentioned above) and the machine that `fetch` is running on. The number of CPUs on the machine will affect the speed of the exp
Have we confirmed that the number of CPU's affects speed of export? Im curious the difference in numbers and this would also be something worth documenting if we know what specs could result in what performance.

2023-12-12 15:38 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
This all SGTM, but I think the above text needs some changing as a result.  Specifically, it would be good if you added all of the detail you uncovered during this investigation and were very precise about the flow of data (including to any involved object storage).

2023-12-12 17:18 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +1. AWS DMS test (uses `COPY`): 33 minutes
I'll note that it can take 18 minutes with the correct parallel table load settings.

2023-12-12 17:19 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +1. AWS DMS test (uses `COPY`): 33 minutes
```
1. AWS DMS test (uses `COPY`): 33 minutes in nightly tests; 18 minutes in preliminary manual testing with parallel individual table loads (future optimization `fetch` can make as well)
```

2023-12-12 17:20 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +4. `COPY FROM` directly without intermediate store: 47 minutes
I'll make a note that there are some testing improvements and testing steps we'll take on in the future.

2023-12-12 17:23 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +The data export process is primarily limited by the dialects supported (mentioned above) and the machine that `fetch` is running on. The number of CPUs on the machine will affect the speed of the exp
This is what I outlined as `future testing` in the section I added in response to your feedback above. I don't think this is immediately necessary to test for this initial RFC. But with how `fetch` is built, we currently default concurrency for tables to how many CPUs the machine has.

2023-12-12 17:28 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
I actually already updated this in a section below:
```
### Options

Data can be imported into Cockroach in one of three ways:

1. `IMPORT INTO` from intermediary store to Cockroach:

- Target table is taken offline
- Supports compression (recommended option because `IMPORT INTO` is much faster than copy, especially with compression).

Source -> Fetch -> Intermediary store -> Target

2. `COPY FROM` (`live` mode) from intermediary store to Cockroach:

- Table is still online and queryable; the intermediary store is used, instead of directly from the database
- Compression can't be supported here because `COPY FROM` currently doesn't have a `decompress` feature

Source -> Fetch -> Intermediary store -> Target

3. Direct `COPY FROM` source database to Cockroach without intermediary store

- Table is still online and query-able
- Not recommended for very large table migrations
- Data is copied from the source to target without intermediary store or files
- Data still passes from the source to `fetch`, but in memory; this means that the RAM specs of the execution machine must be appropriately sized
- Fetch is coordinating the `COPY FROM` and holds access to the DB connections; this is the most direct path `fetch` can support

Source -> Fetch (in memory) -> Target
```

2023-12-12 17:33 UTC, ryanluu12345 commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
I also updated the section you request above:
```
For the initial version, using `COPY` to export data works fine, however we want to move to a model where we can paginate through all the data by selecting data from each of the tables because it allows more flexibility in how we filter through data.

In the case that a `COPY FROM` or `IMPORT INTO` is run and dumps to intermediary files in a store (i.e. AWS S3 or GCP GCS), the data travels from the source database to the machine which is running `fetch`, then to the intermediary store, and then finally to its destination.

In the case that a `COPY` is issued from the source to the target directly, the data is fetched from the source database to the machine that is running `fetch` in memory, formatted in a manner suitable for `COPY` to Cockroach, and copied over to Cockroach.
```

2023-12-12 19:38 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
Weird.  For some reason I couldn't see those edits until now.  I'm probably doing something wrong on my end though, as I'm used to Reviewable reviews.

:lgtm:

2023-12-12 19:38 UTC, ajstorm commented on docs/RFCS/20231113_molt_fetch.md
> +In the case that a `COPY` is issued from the source to the target directly, the data goes directly from source to target.
> I'm probably doing something wrong on my end though, as I'm used to Reviewable reviews.
As evidenced by the fact that GH doesn't even have an LGTM emoji 🤦

2023-12-12 19:39 UTC, ajstorm approved these changes
Thanks for persisting through the review.  This looks good to me.

2023-12-12 20:08 UTC, merged