README: added in instructions for encoding passwords
cockroachdb/molt pull request #77
Opened 2023-11-15 23:06 UTC by ryanluu12345

Release Note: None

2023-11-15 23:07 UTC, ryanluu12345 commented
@ZhouXing19 @Jeremyyang920 @ajstorm this will be the topic we're discussing more in detail tomorrow on how to handle on the code. For now, making clarity changes to the docs.

2023-11-15 23:10 UTC, ryanluu12345 commented
@taroface heads up that I made a DOCS ticket for this companion change: https://cockroachlabs.atlassian.net/browse/DOC-9223

2023-11-16 17:09 UTC, ZhouXing19 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
Is this only for the case where the password is embedded in the url? IIUC, if we have plan to let verify tool be accessed via some other interfaces (such as some UI console), this might not be a blocker?

2023-11-16 18:33 UTC, Jeremyyang920 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
Correct, this is a problem when passed in via a full url. If we do it like we do for the SCT credentials flow and build out the conn string, we can safely escape things.

2023-11-16 18:45 UTC, ryanluu12345 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
Exactly as Jeremy mentioned. However, I think that escaping would be at the layer where we receive the HTTP or gRPC request, before we even pass it over to the `molt` tooling. 

Given that we don't have a web UI just yet for this, we should give a heads up to customers who are using the CLI version with a conn string.

2023-11-17 16:19 UTC, Jeremyyang920 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
I feel like we should move this section up before the sample invocations bit.

2023-11-17 17:54 UTC, Jeremyyang920 requested changes
See the comment about moving the encoding passwords section up so its nearer to where we call it out.

2023-11-17 17:56 UTC, taroface reviewed
Left suggestions and a question on special characters.

2023-11-17 17:56 UTC, taroface commented on README.md
> +See `molt verify --help` for all available parameters. Make sure that your connection strings are properly encoded [(instructions)](#encoding-passwords).
```suggestion
See `molt verify --help` for all available parameters. Make sure that your connection strings are [properly encoded](#encoding-passwords).
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +Make sure that your connection strings are properly encoded [(instructions)](#encoding-passwords).
```suggestion
Make sure that your connection strings are [properly encoded](#encoding-passwords).
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
Can we specify exactly which special characters are problematic?

```suggestion
If your password contains special characters, the MOLT tooling may not be able to parse the password. In the event that this happens, here is what you should do:
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +1. Percent/URL encode the password.
```suggestion
1. Percent/URL-encode the password.
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +2. Substitute the password back into your connection string.
```suggestion
2. Use the encoded password in your connection string.
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +# Original String
```suggestion
# Original connection string
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +# Percent Encoded Password
```suggestion
# Percent-encoded password
```

2023-11-17 17:56 UTC, taroface commented on README.md
> +# Percent Encoded String
```suggestion
# Percent-encoded connection string
```

2023-11-17 17:57 UTC, taroface commented on README.md
> +### Encoding Passwords
```suggestion
### Encoding passwords
```

2023-11-17 19:00 UTC, ryanluu12345 commented on README.md
> +See `molt verify --help` for all available parameters. Make sure that your connection strings are properly encoded [(instructions)](#encoding-passwords).
Done!

2023-11-17 19:00 UTC, ryanluu12345 commented on README.md
> +Make sure that your connection strings are properly encoded [(instructions)](#encoding-passwords).
Done!

2023-11-17 19:01 UTC, ryanluu12345 commented on README.md
> +### Encoding Passwords
Done

2023-11-17 19:02 UTC, ryanluu12345 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
Did this instead: 
```
If your password contains [special characters](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding), the MOLT tooling may not be able to parse the password. In the event that this happens, here is what you should do:
```

2023-11-17 19:04 UTC, ryanluu12345 commented on README.md
> +If your password contains special characters, there is chance that the MOLT tooling will not be able to parse. In the event that this happens, here is what you should do:
I moved it up to the top!

2023-11-17 19:06 UTC, taroface approved these changes
Just one suggestion; otherwise LGTM.

2023-11-17 19:06 UTC, taroface commented on README.md
> +If your password contains [special characters](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding), the MOLT tooling may not be able to parse the password. In the event that this happ
```suggestion
If your password contains [special characters](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding), the MOLT tooling may not be able to parse the password. In the event that this happens, you should:
```

2023-11-17 19:22 UTC, ryanluu12345 commented on README.md
> +If your password contains [special characters](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding), the MOLT tooling may not be able to parse the password. In the event that this happ
Done!

2023-11-17 19:45 UTC, Jeremyyang920 approved these changes
LGTM pending ryans review of the tools copy.

2023-11-17 19:56 UTC, ZhouXing19 commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection string:\n%s\n", url.QueryEscape(inputPassword))
nit: personally i found the `--input` flag a bit unnecessary. Would it be easier to use if the password is just the first arg? I.e. something like:

```go
func EscapePasswordCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "escape-password",
		Short: "Utility to help escape passwords with special characters.",
		Long:  `Utility to help percent-encode passwords that have special characters.`,
		Run: func(cmd *cobra.Command, args []string) {
			if len(args) == 0 {
				cmd.Println("received empty password string")
				return
			}
			passwordStr := args[0]
			cmd.Printf("Substitute the following string in your original connection string:\n%s\n", url.QueryEscape(passwordStr))
		},
	}
	return cmd
}
```

With ux:

```
jane in molt on  main [!?⇡] via 🐹 v1.21.3 on ☁️  (us-east-1) on ☁️  jane@cockroachlabs.com(us-east4) took 10s 
❯ ./molt escape-password 
received empty password string
(base) 
jane in molt on  main [!?⇡] via 🐹 v1.21.3 on ☁️  (us-east-1) on ☁️  jane@cockroachlabs.com(us-east4) 
❯ ./molt escape-password wyuwe$6#dsfjh
Substitute the following string in your original connection string:
wyuwe%23dsfjh
(base) 

```

2023-11-17 19:58 UTC, ZhouXing19 commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection string:\n%s\n", url.QueryEscape(inputPassword))
Also, out of curiosity, do we want to add test for this command?

2023-11-17 20:14 UTC, ryanluu12345 commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection string:\n%s\n", url.QueryEscape(inputPassword))
I'll take this suggestion! I think test wise, it's a very simple function, so it's ok.

2023-11-17 20:19 UTC, ZhouXing19 commented on cmd/escape_password.go
> +	var inputPassword string
The inputPassword var and the StringVarP() can be removed now.

2023-11-17 20:22 UTC, taroface reviewed
One suggestion on the tool output.

2023-11-17 20:22 UTC, taroface commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection url string:\n%s\n", url.QueryEscape(passwordStr))
I assume this is just returning the encoded password and not the whole connection string?

```suggestion
			cmd.Printf("Substitute the following encoded password in your original connection string:\n%s\n", url.QueryEscape(passwordStr))
```

2023-11-17 20:39 UTC, ryanluu12345 commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection url string:\n%s\n", url.QueryEscape(passwordStr))
Yep, it's just the encoded password, not the string.

2023-11-17 20:39 UTC, ryanluu12345 commented on cmd/escape_password.go
> +			cmd.Printf("Substitute the following string in your original connection url string:\n%s\n", url.QueryEscape(passwordStr))
I'll take this suggestion.

2023-11-17 20:40 UTC, ryanluu12345 commented on cmd/escape_password.go
> +	var inputPassword string
Addressed!

2023-11-17 20:41 UTC, ryanluu12345 commented on cmd/escape_password.go
> +	var inputPassword string
```
(⎈|rancher-desktop:N/A)ryanluu@crlMBP-XFFK6Q9QL6MTk1 molt % go run . escape-password ";@;"             
Substitute the following encoded password in your original connection url string:
%3B%40%3B
```

2023-11-17 20:42 UTC, ZhouXing19 approved these changes

2023-11-17 20:50 UTC, merged